### PR TITLE
Adds tests for Index page

### PR DESCRIPTION
**Pull request by manaswinidas**
Adds tests for Index page

### CODE REVIEW

**Review by gedankenstuecke — CHANGES_REQUESTED** [review]
The second tests looks good, but the `test_index_page` test is already implemented under https://github.com/gedankenstuecke/oh_data_uploader/blob/master/main/tests/tests.py#L37

Please either remove your variant or the one in `/main/tests/tests.py` 

Before adding tests it would be good to check CodeClimate on whether given functions are already tested. E.g to see whether the `main/views.py` are already covered by tests you could check this link: https://codeclimate.com/github/gedankenstuecke/oh_data_uploader/code?sort=test_coverage

**Comment by manaswinidas** [comment]
Yes I'm removing my variant

**Comment by manaswinidas** [comment]
Done!

**Review by gedankenstuecke — APPROVED** [review]

**Comment by gedankenstuecke** [comment]
Thanks!

**Pull request merged**
