### PR TITLE
Added testcase for list_files function

### PR DESCRIPTION
**Pull request by troublemagnet**
Made a mock get url to test the list_files function.

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
Could you fix all the style violations that hound is complaining about before we go on? 😄

**Comment by troublemagnet** [comment]
Yes, I'm on it.

**Comment by gedankenstuecke** [comment]
Great, thanks!

**Comment by troublemagnet** [comment]
@gedankenstuecke Done :sweat_smile:

**Review by gedankenstuecke — CHANGES_REQUESTED** [review]
This looks good so far. I have only two remarks: 

1. You mock the get-files endpoint. But your test then only `assert`s that the page loads. It would be good if you could an assertion on whether the page renders the presence of that file. 

2. This is more style, but could it be that you're using `tabs` instead of `spaces` for the indentation? At least if you look on your indentations here on GitHub the indentation looks very different from the existing code?

**Comment by troublemagnet** [comment]
@gedankenstuecke  About the first one, I was unsure about the same. :sweat_smile: 
Yes it looked a little different locally also, but flake8 was reporting many errors. Hence, I had to change the style to ensure that it complies with flake8.

**Comment by troublemagnet** [comment]
@gedankenstuecke I was wondering if this assertion is enough to confirm the rendering?

**Comment by gedankenstuecke** [comment]
I fixed the indentation, please have a look now to see what `flake8` will also accept as correct indentation 😄

**Comment by troublemagnet** [comment]
@gedankenstuecke Sorry for the ugly version, this version definitely looks neater and more legible.

**Comment by gedankenstuecke** [comment]
The assertion should be enough. I just replaced the `assertIn(…,str()` with `assertInHTML` instead, as `Django` brings this function on its own. Let's see whether that still passes

**Review by gedankenstuecke — APPROVED** [review]

**Comment by gedankenstuecke** [comment]
Ok, apparently `assertInHTML` is fickle, (c.f. https://stackoverflow.com/questions/38800089/django-assert-failure-assertinhtmlhello-htmlhello-html) so I reverted to `assertIn` and will merge then

**Pull request merged**
