### PR TITLE
Improve Pipfile

### LINKED ISSUE #12: Update Pipfile
All the other Open Humans projects are now moving from using `pip` and `virtualenv`/`anaconda` separately to using `pipenv`, e.g. see https://github.com/OpenHumans/oh-proj-management. 

We should follow along with this project as it's much nicer and easier. To do this the `requirements.txt` needs to be used to seed the `Pipfile` and a `Pipfile.lock` needs to be created. Afterwards the `Pipfile` should be set up so it doesn't use fixed versions any more. Both `Pipfile` and `Pipfile.lock` should be added to this repo

Additionally the `INSTALL.md` needs to be updated to reflect this.

### PR DESCRIPTION
**Pull request by manaswinidas**
Improvements in Pipfile. 
Closes #12

### CODE REVIEW

**Review by gedankenstuecke — CHANGES_REQUESTED** [review]
This looks good! But there are still some minor things missing to close #12:

1. `open-humans-api` should be installed right from `PyPi` like all other packages in the `Pipfile`, e.g. remove all the references to GitHub.
2. The `Pipfile.lock` was not updated. Please run `pipenv install` after updating the `Pipfile` and commit the new `Pipfile.lock` this will generate.

**Comment by manaswinidas** [comment]
Is it alright, now?

**Review by gedankenstuecke — APPROVED** [review]
Yes, that's great! Thanks!

**Comment by manaswinidas** [comment]
Thanks for reviewing!

**Pull request merged**
