### PR TITLE
Add list and delete functionality

### PR DESCRIPTION
**Pull request by jasmine1997**
Regarding #1 
image

Since this was my first PR, I focussed more on getting things to work, so I'm open to suggestions on the design and placement of the list (whether as a separate template or a partial in overview etc)

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
Hey @jasmine1997 that looks great! Unfortunately there's now some conflicts after @madprime did a major restructuring of the app structure to make sure that our code is more reusable. Would you be willing to adapt your code to work in this new structure?

**Comment by jasmine1997** [comment]
Sure :)

**Comment by gedankenstuecke** [comment]
Sorry for taking so long to look at this! I just gave it a try locally and the list itself works fine. Unfortunately deleting a file from the list doesn't work. 

I think this is a result of the `open-humans-api` delete function being broken right now. @madprime did you update to the latest version on `Pypi`?

**Comment by gedankenstuecke** [comment]
Ah, I found the problem, the fixed `open-humans-api` library was pushed to `PyPi` by @madprime but it's not yet in our Pipfile.lock. If you upgrade it, it works. 

@jasmine1997: To fix you can just run `pipenv update open-humans-api` on your end and commit the new `Pipfile.lock` too, then it will work.

**Review by gedankenstuecke — APPROVED** [review]
fixed the pipfile independently and ready to merge now! 👍

**Pull request merged**
