### PR TITLE
Main/views coverage increased

### PR DESCRIPTION
**Pull request by troublemagnet**
Aiming to achieve ~100% coverage for main/views.py

### CODE REVIEW

**Comment by troublemagnet** [comment]
@gedankenstuecke Not sure about how to fix the code smell reported..

**Comment by gedankenstuecke** [comment]
Thanks for the contribution first of all, I started playing around to see how we can fix it, by now it's only a single line too much :D

**Comment by troublemagnet** [comment]
@gedankenstuecke That was a great addition :D Yay it's fixed

**Comment by gedankenstuecke** [comment]
It's a bit of cheating, but it works now and I'll merge it 👍 Thanks for the great tests!

**Review by gedankenstuecke — APPROVED** [review]

**Pull request merged**
