### PR TITLE
Add support for multiple file upload

### LINKED ISSUE #1: Upload behavior
Right now the uploader 

- will always delete all the files that are already associated with a given project if a user uploads a new file. 
- users can only upload a single file, there is no way to upload multiple files. 

This behaviour should be changed to allow users to 
- keep older files in their account
- allow multiple files being stored

Ideally this would also allow users to display the files already in their accounts and give the option to delete individual files?

### PR DESCRIPTION
**Pull request by jasmine1997**
Removed columns 'file_description' and 'file_tags' from ProjectConfiguration and made a separate table called FileMetaData with columns 'name' (for representation), 'description' and 'tags' for metadata.

Fixes #1

### CODE REVIEW

**Review by gedankenstuecke — CHANGES_REQUESTED** [review]
Thanks for cleaning up all the hound messages and the great work! The workflow does what it's supposed to do and that is awesome, really well done! 🎉 

There are some minor things that need to be improved before I can merge it:

1. I think there is a current migration missing, when running `manage.py migrate` it will say that there's changes to the file `model` that's not yet in a migration. Please add that migration on your end with `manage.py makemigrations`

2. On the `project-admin` page for adding new files (`http://127.0.0.1:5000/project-admin/config-file-settings`) there is a problem with deleting entered data. 

Let's say I go to the page, enter the metadata for the first file and then press `add file` without pressing `save updates` first: This will add a second file, but while wiping all the information I already entered for the first file. The same thing happens if I click on `delete file` for the second file, again the first file will be wiped. It would be cool if this information would be restored so that people don't have to re-enter everything (I had to do it 4 times because I always accidentally clicked `add file` instead of `save`)

3. The file upload form at `http://127.0.0.1:5000/overview` works in itself, alas: It does not show which file I already entered to be uploaded. E.g. I pick a file that should be uploaded for `File 1` but after doing this there is no visual feedback that I did so. The old form would show the name of the file to the user to give this feedback. This should be re-added to the form.

**Comment by gedankenstuecke** [comment]
Oh, and another minor issue: some of the functions are flagged as being too complex by `codeclimate`, see https://codeclimate.com/github/gedankenstuecke/oh_data_uploader/pull/45

If those could be refactored to minimize these issues that would be perfect. 🙂

**Comment by jasmine1997** [comment]
@gedankenstuecke Thanks for reviewing!
I tried fixing the codeclimate issues, the 2 remaining ones seem to be false positives.

**Review by mcescalante — COMMENTED** [review]
I agree that the 2 codeclimate errors seem to be false positives. I've tested this PR out:

2 of 3 previous issues are fixed:

1. migration
2. project admin add data before saving (now works as described, allows multiple entries before save)

On 3. - I upload a file via the new uploader, and I get a successful upload, but when I go back to the homepage the "file list" displayed allows me to upload another file even though I already uploaded a file for this entry (successfully). I am not sure if this is the expected behavior, but I think it makes sense to allow 1 file per file list entry, so allowing me to re-upload confused me. Here's a GIF showing this:



I'll let @gedankenstuecke take a look and weigh in on that last upload comments, but great job fixing the first two requested changes and on this PR overall. There are a lot of changes here! 😄

**Review by gedankenstuecke — APPROVED** [review]
That's a job well done! Thanks @jasmine1997! 🎉 I just tested everything locally and that works perfectly. 

@mcescalante: Now that people can manage their own files it's okay that people can upload two different files that belong to the same file/tag combination. E.g. you might want to upload a newer version if your data, or track longitudinal things. So I'm fine with the implementation as is. 

There's just a minor display bug I'll just open another issue for this as it doesn't prohibit merging this. 

Oh, and yeah: CodeClimate gives a false positive here, I set this specific error pair on the whitelist so it will hopefully be ignored in the future.

**Pull request merged**
